---
driver:
  network:
    - ['forwarded_port', { guest: 9999, host: 9999 } ]
  customize:
    memory: 4096
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - 'looker'
    attributes:
      looker:
        startup_script: ENV['LOOKER_STARTUP_SCRIPT_URL']
        jar_file: ENV['LOOKER_JAR_URL']
